org: kou3141
app: seknot-api
service: seknotApi

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x

  stage: dev
  region: ap-northeast-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/Users'
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/Wallets'
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/Tokens'
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/ApiKeys'

functions:
  systemService:
    handler: src/functions/SystemService/handler.handler
    events:
      - http:
          path: /ping
          method: get
  walletService:
    handler: src/functions/WalletService/handler.handler
    events:
      - http:
          path: /wallet
          method: get
      - http:
          path: /wallet
          method: post
      - http:
          path: /wallet/{walletId}
          method: get
      - http:
          path: /wallet/balance/{walletId}
          method: get

package:
  exclude:
    - docs/**
    - node_modules/**
    - templates/**
    - .eslintrc.json
    - LICENSE
    - README.md
    - package-lock.json

plugins:
  - serverless-offline
