openapi: 3.0.0
info:
  title: Seknot API
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /info/ping:
    get:
      summary: システム応答確認
      tags:
        - System
      responses:
        '200':
          description: System is active!
      operationId: get-ping
      description: サービスの応答確認用
      x-internal: true
      x-amazon-apigateway-integration:
        type: aws_proxy
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:126630733710:function:seknot-getSystemStatus-dev/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      properties:
        id:
          type: integer
          description: 自動生成される一意のid
        userName:
          type: string
          description: 共同developerの招待などに使用
        email:
          type: string
          format: email
        createDate:
          type: string
          format: date
          description: User作成日
        password:
          type: string
          description: |
            PasswordのHash
      required:
        - id
        - userName
        - email
        - password
    Token:
      title: Token
      type: object
      description: ''
      properties:
        id:
          type: integer
        contractAddress:
          type: string
        name:
          type: string
        totalSupply:
          type: integer
        symbol:
          type: string
        version:
          type: number
        createDate:
          type: string
          format: date
      required:
        - id
        - contractAddress
        - name
        - totalSupply
        - symbol
    Wallet:
      title: Wallet
      type: object
      description: ''
      properties:
        id:
          type: string
          description: Wallet管理用id
        address:
          type: string
        service:
          type: string
          description: 関連付けられたservice
        tokens:
          type: array
          items:
            type: string
      required:
        - id
        - address
        - service
    ApiKey:
      title: ApiKey
      type: object
      properties:
        key:
          type: string
        serviceId:
          type: string
        createDate:
          type: string
          format: date
      required:
        - key
        - serviceId
  securitySchemes: {}
